### ISSUE TITLE
Can't access auth()->user() in AppServiceProvider boot()

### ISSUE THREAD

**Issue by adddz** [livewire-ui/spotlight#16]
The documentation mentions that you can register the command in the `boot()` method of the `AppServiceProvider` file.

```
use \App\SpotlightCommands\CreateUser;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Spotlight::registerCommand(CreateUser::class);

        // You can also register commands conditionally
        Spotlight::registerCommandIf($user->isAdmin(), CreateUser::class);
        Spotlight::registerCommandUnless($user->isSuspended(), CreateUser::class);
    }

}
```

This is not working because `$user` or `auth()->user()` cannot be accessed during the `boot()` method.

Any ideas on how to conditionally register commands based on the user?

**Comment by PhiloNL** [comment]
Hi @adddz,

That's correct, there's a PR to resolve this and will be available soon https://github.com/livewire-ui/spotlight/pull/15

**Comment by PhiloNL** [comment]
Hi @adddz
You can now use the `shouldBeShown` method to do this:

- https://github.com/livewire-ui/spotlight/releases/tag/0.1.7
- https://github.com/livewire-ui/spotlight/blob/master/CHANGELOG.md

**Comment by adddz** [comment]
Thank you so much! Could you please port this feature to the PHP 7.4 version as well, please?
