### ISSUE TITLE
Allow to use fuse.js from build instead of CDN

### ISSUE THREAD

**Issue by erikgaal** [livewire-ui/spotlight#17]
At this moment, `fuse.js` is included with Spotlight through the jsDelivr CDN. Some users might prefer to include these assets through their own build process.

As a sidenote, `fuse.js` isn't locked to a specific version at this moment which might cause uninteded breaking changes.

https://github.com/livewire-ui/spotlight/blob/ceb4005ee817b64ebf86526d2b0706ea6b4227ba/resources/views/spotlight.blade.php#L2

**Comment by PhiloNL** [comment]
Thanks @erikgaal 😄 
Coming up in the next release: https://github.com/livewire-ui/spotlight/pull/19

**Comment by PhiloNL** [comment]
Now available, also locked the dependency 👌
