### ISSUE TITLE
Not able to interact with the component

### ISSUE THREAD

**Issue by StanBarrows** [livewire-ui/spotlight#2]
HeyHey, Cool package you have there. Excited to test it out!

I just ran into a problem but I'm not able to solve it. I've livewire alrdy preinstalled and just added the component like you mentioned within the docs.

After I hit the start page, I can see the overlay but can not close or interact with it. Any ideas?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10268813/115795421-2e491a80-a3d0-11eb-8ab8-0beb7c879bc3.png">

```
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">

   <link href="{{ mix('css/app.css') }}" rel="stylesheet">
      
    @livewireStyles

</head>
<body class="bg-gray-50">
@include('layouts.partials._navigation')
@yield('content')
@include('layouts.partials._footer')
@include('layouts.partials._flash')
<script src="{{ mix('js/app.js')}}"></script>
@livewire('livewire-ui-spotlight')
@livewireScripts
</body>
</html>
```

I've also created the test component.

```
<?php

namespace App\Http\Livewire\Commands;

use Illuminate\Contracts\Auth\StatefulGuard;
use LivewireUI\Spotlight\Spotlight;
use LivewireUI\Spotlight\SpotlightCommand;

class Logout extends SpotlightCommand
{
    protected string $name = 'Logout';

    protected string $description = 'Logout out of your account';

    public function execute(Spotlight $spotlight, StatefulGuard $guard): void
    {
        $guard->logout();
        $spotlight->redirect('/');
    }
}

```

Cheers,

**Comment by PhiloNL** [comment]
Hey Stan,
Thanks for trying Spotlight 😄

Do you get any errors in your browser console? Seems like a Javascript issue.

Thanks!

**Comment by PhiloNL** [comment]
I see I have forgotten to mention that AlpineJS is a dependency. So this might be missing which is breaking the Javascript.

CDN:
`<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>`

NPM:
`npm i alpinejs`

**Comment by StanBarrows** [comment]
That was the trick! =) Thank you

**Comment by PhiloNL** [comment]
Great! 😄
