### ISSUE TITLE
Safari tries to fill username

### ISSUE THREAD

**Issue by quarterdeck** [livewire-ui/spotlight#25]
<img width="554" alt="Screenshot 2021-05-27 at 13 51 26" src="https://user-images.githubusercontent.com/56797103/119831457-34617800-bef5-11eb-913e-5ccd533207bb.png">

**Comment by quarterdeck** [comment]
Upon further investigation this seems like an absolutely crazy Safari bug and I'm not sure if it can be worked around or not.

I noticed that this was only happening on one page of our app. So I systematically commented out each section of HTML to see if any block was affecting it and I found one!

I narrowed it down to a single <p> tag which contained the text "Welcome back,". I thought the comma might be causing an issue (no idea why) so I removed it. No change.

I thought the word "back" might be making Safari think this was a login page for some reason? So I removed it and it fixed the issue! Crazy.

Out of curiosity I tried removing "Welcome" and adding "back" back in. Still didn't re-occur. ?!

So it seems only the combination of words "welcome back" causes this to happen. Absolutely no idea why. To confirm I chose another page randomly and put the phrase "welcome back" in a random position on the page and low and behold it caused this to happen again.

For some reason the presence of these words on the page is adding aria-label="autofill password" to the Shadow DOM of the input field.

Easily the most bizarre bug I've ever come across.

**Comment by quarterdeck** [comment]
On further consideration I don't think it's a bug. I think Safari is assuming any page with "Welcome Back" on it is a login page and enabling this behaviour. Therefore I think it's intended.

**Comment by laurensgroeneveld** [comment]
I can confirm, created a HTML page with just a `p` and an `input`:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
    <p>Welcome back</p>
    <input type="text">
</body>
</html>
```

This does indeed show a password option if I open this in Safari and focus the input:

<img width="169" alt="image" src="https://user-images.githubusercontent.com/39056299/119967569-c7a9b480-bfac-11eb-9e79-ec510ac70b3a.png">

Curiously enough, adding a `style="display: none;` to the `p` does no longer show the password dropdown.

**Comment by quarterdeck** [comment]
Nice one. I found that using a non-breaking space prevents the behaviour.

```
<p>welcome&nbsp;back</p>
```

**Comment by infostreams** [comment]
LOL 😂 Make sure to add a comment (with a link) to your code to document why that ```&nbsp;``` is there. I'm sure someone would just accidentally remove it otherwise.

**Comment by val-o** [comment]
It seems the same applies to "Sign In"
![image](https://user-images.githubusercontent.com/9393189/119973198-02bfde00-bfd5-11eb-8a8f-0d0bb5986578.png)

**Comment by mattijv** [comment]
"Log in" works too. I tried a couple other languages (Finnish, German, French, Chinese) but the issue/feature seems to only happen with English (although I did use Google Translate, so I can't guarantee I used the right idioms).

**Comment by chrisvasey** [comment]
This bug is top of hacker news right now, there have been a lot of comments around why this is [here](https://news.ycombinator.com/item?id=27313284).

**Comment by IThinkImOKAY** [comment]
Maybe welcome back causes safari to think you are being welcomed back to the website and would like to sign back in?

**Comment by elstgav** [comment]
Does it respect `autocomplete=“off”`? You may be able to disable it with some form of [the autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) 🤔

**Comment by PhiloNL** [comment]
Interesting issue 🤓 feel free to continue the discussion.
I am closing the issue as it's not related to Spotlight.

**Comment by vadim-isakov** [comment]
Safari offers autocomplete if there is a word "username" inside of a label.

There are 2 solutions I found to prevent this:
1. Adding the word "search" to the field's name (label and input)
2. Replace the label's text character with its Unicode equivalent. For example: replace "a" with "\u0430".
