### ISSUE TITLE
Closing Spotlight during dependency search doesn't reset flow

### ISSUE THREAD

**Issue by nathanheffley** [livewire-ui/spotlight#3]
I am not sure if this is intentional, but I found it somewhat confusing that if I created a command with dependencies (something simple like in the readme), if I closed the Spotlight element while it was prompting me to search for a dependency, the next time I opened the spotlight (unless there had been a full page reload) it would still be asking me to search for the dependency, and then only way to clear it was to either finish searching or to reload the page.

I think it would be more intuitive if the spotlight element always reset itself when it closed, so that if the user accidentally selects the wrong option they don't get stuck in that flow and forced to reload the page.

**Comment by PhiloNL** [comment]
Hey @nathanheffley, thanks for the feedback. That can indeed be confusing and I agree it's more intuitive to reset when the element is closed so a user doesn't get stuck in that flow and is forced to reload the page. I've just released an update to reset the state if the component is closed 😄

- https://github.com/livewire-ui/spotlight/releases/tag/0.1.3
- https://github.com/livewire-ui/spotlight/blob/0.1.3/CHANGELOG.md
