### ISSUE TITLE
Alpine Error: "SyntaxError: Unexpected token '}'"

### ISSUE THREAD

**Issue by SimonBarrettACT** [livewire-ui/spotlight#33]
I'm running v1.0.0 of Spotlight and have implemented the example logout command.

When typing 'Logout', the dropdown does not appear and the following error is sent to the console:

```
[Warning] Alpine Error: "SyntaxError: Unexpected token '}'" (app.js, line 123)

Expression: ""
Element: – 
<template x-for="(item, i) in filteredItems()" :key>…</template>

<template x-for="(item, i) in filteredItems()" :key>…</template>
[Error] SyntaxError: Unexpected token '}'
	handleError (app.js:130)
	tryCatch (app.js:142)
	(anonymous function) (app.js:563)
	forEach
	handleForDirective (app.js:561)
	(anonymous function) (app.js:1751)
	forEach
	resolveBoundAttributes (app.js:1711)
	updateElement (app.js:1687)
	(anonymous function) (app.js:1643)
	walk (app.js:98)
	walk (app.js:102)
	walk (app.js:102)
	walk (app.js:102)
	walk (app.js:102)
	walkAndSkipNestedComponents (app.js:1598)
	updateElements (app.js:1640)
	(anonymous function) (app.js:1548)
	later (app.js:114)
```

Spotlight v0.1.8 does not exhibit this behaviour.

I'm using:

Livewire v2.5.1
Alpine v3.2.1
Laravel v8.49.1

Love the component and will be using it in several projects.
Thanks

**Comment by fefo-p** [comment]
Same here, though the output in my case has line number differences:
```javascript
[Error] SyntaxError: Unexpected token '}'
	Function (alpine.js:2)
	saferEval (alpine.js:118)
	(anonymous function) (alpine.js:520)
	forEach
	handleForDirective (alpine.js:518)
	(anonymous function) (alpine.js:1703)
	forEach
	resolveBoundAttributes (alpine.js:1663)
	updateElement (alpine.js:1639)
	(anonymous function) (alpine.js:1595)
	walk (alpine.js:90)
	walk (alpine.js:94)
	walk (alpine.js:94)
	walk (alpine.js:94)
	walk (alpine.js:94)
	walkAndSkipNestedComponents (alpine.js:1550)
	updateElements (alpine.js:1592)
	(anonymous function) (alpine.js:1500)
	later (alpine.js:106)
```

Is there any other useful info that I can provide?
Please let me know

**Comment by PhiloNL** [comment]
Hi both,

Thanks for trying Spotlight.
Unfortunately, I'm unable to replicate this error using the exact same versions of Laravel, Livewire, and Alpine (fresh install).
I can further investigate but this will require you to set up a demo repository that replicates the issue.

**Comment by fefo-p** [comment]
Maybe it makes a difference  mentioning that I'm using Laravel with Jetstream, Tailwind (JIT mode), AlpineJs, Livewire, & Laravel/permissions?
I mention this as maybe the difference is on how the app.css & app.js get compiled... don't know.

My webpack.mix.js is like the following, updated to use JIT
```javascript
mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css')
    .options({
        postCss: [
            require('postcss-import'),
            require('autoprefixer'),
            require('@tailwindcss/jit'),
        ]
    });

if (mix.inProduction()) {
    mix.version();
}
```

**Comment by PhiloNL** [comment]
Hi @fefo-p 
I would recommend creating a fresh installation of Laravel, install Spotlight, verify that it is working, next, add each dependency step by step and see if Spotlight breaks to figure out what is causing the issue. I'm using Spotlight with Jetstream and Tailwind as well without any issues.

**Comment by fefo-p** [comment]
Will do, Thanks @PhiloNL

**Comment by philipmclifton** [comment]
Did you resolve this issue, I am seeing the same thing.

**Comment by fefo-p** [comment]
Unfortunately no, haven't had the time

**Comment by mrpritchett** [comment]
I'm also getting this issue. Trying to dig in now.

**Comment by pavlentij** [comment]
I had the same issue, but the problem was in the old Alpine.js version. 
My application had v2.* and after the upgrade to v3.0 everything became working as it should.

**Comment by nusoft** [comment]
> I'm also getting this issue. Trying to dig in now.

@mrpritchett did you manage to solve this issue? I'm getting the same error

**Comment by mrpritchett** [comment]
@nusoft It was an issue with versioning as described above. Once I updated to v3 of AlpineJS, everything worked fine.
