### ISSUE TITLE
Target [Illuminate\Contracts\Auth\StatefulGuard] is not instantiable.

### ISSUE THREAD

**Issue by sandy15d** [livewire-ui/spotlight#38]
`<?php

namespace LivewireUI\Spotlight\Commands;

use Illuminate\Contracts\Auth\StatefulGuard;
use LivewireUI\Spotlight\Spotlight;
use LivewireUI\Spotlight\SpotlightCommand;

class Logout extends SpotlightCommand
{

    protected string $name = 'Logout';
    protected string $description = 'Logout out of your account';
    public function execute(Spotlight $spotlight, StatefulGuard $guard): void

    {

        $guard->logout();

        $spotlight->redirect('/');

    }
}
`

**Comment by PhiloNL** [comment]
Works just fine here.

**Comment by sandy15d** [comment]
but when i click on logout this kind of error arrives 

Target [Illuminate\Contracts\Auth\StatefulGuard] is not instantiable.

**Comment by PhiloNL** [comment]
Not sure, if you create a fresh installation of Laravel with Spotlight installed, reproduce the problem and share this via a Github repository I can take a look.

**Comment by modernben** [comment]
I'm getting this as well on a project that uses the laravel/ui package.

Laravel: 8.73.2
PHP: 7.4.26
Laravel UI: ^3.3

**Comment by modernben** [comment]
I created my own and changed it to `auth()->logout()` and it works

**Comment by sandy15d** [comment]
Hi Ben...

Pls Can you share full code if possible...

It will be very helpful for me

**Comment by modernben** [comment]
@sandy15d 

```php
<?php

namespace App\Spotlight;

use LivewireUI\Spotlight\Spotlight;
use LivewireUI\Spotlight\SpotlightCommand;
use Illuminate\Contracts\Auth\StatefulGuard;
use LivewireUI\Spotlight\SpotlightSearchResult;
use LivewireUI\Spotlight\SpotlightCommandDependency;
use LivewireUI\Spotlight\SpotlightCommandDependencies;

class Logout extends SpotlightCommand
{
    protected string $name = 'Logout';

    protected string $description = 'Logout out of your account';

    public function execute(Spotlight $spotlight): void
    {
        auth()->logout();
        $spotlight->redirect('/');
    }
}
```

Then update `config/livewire-ui-spotlight.php` 


```php
'commands' => [
    App\Spotlight\Logout::class,
],
```

**Comment by am-chris** [comment]
I also just ran into this issue after upgrading from Laravel 6 to Laravel 8 with the Laravel UI package.
