### ISSUE TITLE
RegisterCommandIf Not working

### ISSUE THREAD

**Issue by sandy15d** [livewire-ui/spotlight#39]
` public function boot()
    {

       Spotlight::registerCommandIf(Auth::check() && Auth::user()->role == 'A',Logout::class);
    }`

**Comment by PhiloNL** [comment]
@sandy15d please use the `shouldBeShown` method on the command when working with dependencies that need to be resolved:

```php
    public function shouldBeShown(Request $request): bool
    {
        return $request->user()->role == 'A;
    }
```

More info: https://github.com/livewire-ui/spotlight#register-commands
