### ISSUE TITLE
add x-cloak  to remove loading flash

### ISSUE THREAD

**Issue by felixsc** [livewire-ui/spotlight#4]
I first want to thank you @PhiloNL for this amazing package!

**Problem**
I'm seeing the spotlight component flash up occasionally before its `display: none` seems to be applied.

**Proposed solution**
Add x-cloak to the component, [as it is best practice](https://github.com/alpinejs/alpine#x-cloak) in Alpine

Should you not want this, is there a way to publish the view files of the spotlight component?

**Comment by PhiloNL** [comment]
Thanks @felixsc 🙏  I'm super happy to hear you like it.
That should definitely be on the component, completely forgot to add it 🙈  
Should be fixed now 😄

- https://github.com/livewire-ui/spotlight/releases/tag/0.1.3   
- https://github.com/livewire-ui/spotlight/blob/0.1.3/CHANGELOG.md

**Comment by felixsc** [comment]
Awesome! Thanks for the quick response 👍
