### ISSUE TITLE
Commands specific to a route

### ISSUE THREAD

**Issue by vinhais** [livewire-ui/spotlight#9]
Hi,
It would be interesting to have something that allows some commands to appear only on one route, for example:

Command 1 -> all
Command 2 -> dashboard
Command 3 -> profile.*

**Comment by PhiloNL** [comment]
Hi,

That's possible, by conditionally registering commands. For example:

```php
Spotlight::registerCommandIf(request()->routeIs('dashboard'), CommandTwo::class);
Spotlight::registerCommandIf(request()->routeIs('profile.*'), CommandThree::class);
```

**Comment by vinhais** [comment]
Through config, is it not possible?

**Comment by PhiloNL** [comment]
@vinhais nope, you will have to register the commands in your `AppServiceProvider` for example when using this syntax.
